"""followers

Revision ID: 852b25d1a599
Revises: 26ae4377bb24
Create Date: 2021-06-04 16:02:14.038717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852b25d1a599'
down_revision = '26ae4377bb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
